=== CrazyPokemonDev/JarvisButlerBot/JarvisButlerBot/Training/TrainingData.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "MessageText",
      "ChatType",
      "MessageType",
      "HasReplyToMessage",
      "TaskId"
    ],
    "properties": {
      "MessageText": {
        "$id": "#/items/properties/MessageText",
        "type": "string",
        "title": "Message Text",
        "pattern": "^(.*)$"
      },
      "ChatType": {
        "$id": "#/items/properties/ChatType",
        "type": "string",
        "enum": [
          "Private",
          "Group",
          "Supergroup",
          "Channel"
        ],
        "title": "Chat Type",
        "pattern": "^(.*)$"
      },
      "MessageType": {
        "$id": "#/items/properties/MessageType",
        "type": "string",
        "enum": [
          "Text",
          "Photo",
          "Audio",
          "Document",
          "Poll",
          "Video",
          "Voice",
          "Animation"
        ],
        "title": "The Messagetype Schema"
      },
      "HasReplyToMessage": {
        "$id": "#/items/properties/HasReplyToMessage",
        "type": "string",
        "enum": [
          "True",
          "False"
        ],
        "title": "Whether the message has a message it replies to"
      },
      "TaskId": {
        "$id": "#/items/properties/TaskId",
        "type": "string",
        "title": "The Taskid Schema",
        "examples": [
          "jarvis.default.ping.ping"
        ],
        "pattern": "^(.*)$"
      }
    }
  }
}

=== CrazyPokemonDev/JarvisButlerBot/JarvisButlerBot/Training/Ping.json
[
	{ "MessageText": "Jarvis, are you there?", "ChatType": "Private", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "hey JARVIS, u there?", "ChatType": "Group", "MessageType": "Animation", "HasReplyToMessage": "True", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "/ping@JarvisButlerBot", "ChatType": "Private", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "Is @JarvisButlerBot still alive?", "ChatType": "Supergroup", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "@JarvisButlerBot, can I speak to you for a second?", "ChatType": "Group", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "/ping", "ChatType": "Private", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "Where is our butler anyway?", "ChatType": "Supergroup", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "There he is, my precious JARVIS!", "ChatType": "Group", "MessageType": "Text", "HasReplyToMessage": "True", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "I wonder whether @JarvisButlerBot is up again...", "ChatType": "Group", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "I demand you show yourself right now!", "ChatType": "Private", "MessageType": "Text", "HasReplyToMessage": "True", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "jarvis is back eh", "ChatType": "Supergroup", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "omg thats jarvis", "ChatType": "Group", "MessageType": "Text", "HasReplyToMessage": "True", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "ping pong @JarvisButlerBot", "ChatType": "Group", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "Calling JARVIS, over", "ChatType": "Private", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "r u there", "ChatType": "Private", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "r u there", "ChatType": "Supergroup", "MessageType": "Text", "HasReplyToMessage": "True", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "jarvis online eh", "ChatType": "Supergroup", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "ping", "ChatType": "Private", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "@JARVISBUTLERBOT, COME HERE RIGHT NOW!", "ChatType": "Supergroup", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "hey doodoohead", "ChatType": "Private", "MessageType": "Text", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "waddup bro", "ChatType": "Group", "MessageType": "Text", "HasReplyToMessage": "True", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "is ma bro jarvis in da house", "ChatType": "Supergroup", "MessageType": "Text", "HasReplyToMessage": "True", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "I wish to speak to the butler of this place, if that's possible, thank you.", "ChatType": "Supergroup", "MessageType": "Text", "HasReplyToMessage": "True", "TaskId": "jarvis.default.ping.ping" },
	{ "MessageText": "hey!", "ChatType": "Private", "MessageType": "Animation", "HasReplyToMessage": "False", "TaskId": "jarvis.default.ping.ping" }
]
